// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from '@flowglad/node-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import Flowglad from '@flowglad/node';

export const metadata: Metadata = {
  resource: 'products',
  operation: 'write',
  tags: [],
  httpMethod: 'put',
  httpPath: '/api/v1/products/{id}',
  operationId: 'products-edit',
};

export const tool: Tool = {
  name: 'update_products',
  description: 'Update Product',
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      product: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
          },
          active: {
            type: 'boolean',
          },
          catalogId: {
            type: 'string',
          },
          description: {
            type: 'string',
          },
          displayFeatures: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                enabled: {
                  type: 'boolean',
                },
                label: {
                  type: 'string',
                },
                details: {
                  type: 'string',
                },
              },
              required: ['enabled', 'label'],
            },
          },
          externalId: {
            type: 'string',
          },
          imageURL: {
            type: 'string',
          },
          livemode: {
            type: 'boolean',
          },
          name: {
            type: 'string',
          },
          organizationId: {
            type: 'string',
          },
          pluralQuantityLabel: {
            type: 'string',
          },
          singularQuantityLabel: {
            type: 'string',
          },
        },
        required: ['id'],
      },
      price: {
        anyOf: [
          {
            type: 'object',
            description:
              'A subscription price, which will have details on the interval, default trial period, and setup fee (if any).',
            properties: {
              id: {
                type: 'string',
              },
              type: {
                type: 'string',
                enum: ['subscription'],
              },
              active: {
                type: 'boolean',
              },
              currency: {
                type: 'string',
                enum: [
                  'USD',
                  'AED',
                  'AFN',
                  'ALL',
                  'AMD',
                  'ANG',
                  'AOA',
                  'ARS',
                  'AUD',
                  'AWG',
                  'AZN',
                  'BAM',
                  'BBD',
                  'BDT',
                  'BGN',
                  'BIF',
                  'BMD',
                  'BND',
                  'BOB',
                  'BRL',
                  'BSD',
                  'BWP',
                  'BYN',
                  'BZD',
                  'CAD',
                  'CDF',
                  'CHF',
                  'CLP',
                  'CNY',
                  'COP',
                  'CRC',
                  'CVE',
                  'CZK',
                  'DJF',
                  'DKK',
                  'DOP',
                  'DZD',
                  'EGP',
                  'ETB',
                  'EUR',
                  'FJD',
                  'FKP',
                  'GBP',
                  'GEL',
                  'GIP',
                  'GMD',
                  'GNF',
                  'GTQ',
                  'GYD',
                  'HKD',
                  'HNL',
                  'HTG',
                  'HUF',
                  'IDR',
                  'ILS',
                  'INR',
                  'ISK',
                  'JMD',
                  'JPY',
                  'KES',
                  'KGS',
                  'KHR',
                  'KMF',
                  'KRW',
                  'KYD',
                  'KZT',
                  'LAK',
                  'LBP',
                  'LKR',
                  'LRD',
                  'LSL',
                  'MAD',
                  'MDL',
                  'MGA',
                  'MKD',
                  'MMK',
                  'MNT',
                  'MOP',
                  'MUR',
                  'MVR',
                  'MWK',
                  'MXN',
                  'MYR',
                  'MZN',
                  'NAD',
                  'NGN',
                  'NIO',
                  'NOK',
                  'NPR',
                  'NZD',
                  'PAB',
                  'PEN',
                  'PGK',
                  'PHP',
                  'PKR',
                  'PLN',
                  'PYG',
                  'QAR',
                  'RON',
                  'RSD',
                  'RUB',
                  'RWF',
                  'SAR',
                  'SBD',
                  'SCR',
                  'SEK',
                  'SGD',
                  'SHP',
                  'SLE',
                  'SOS',
                  'SRD',
                  'STD',
                  'SZL',
                  'THB',
                  'TJS',
                  'TOP',
                  'TRY',
                  'TTD',
                  'TWD',
                  'TZS',
                  'UAH',
                  'UGX',
                  'UYU',
                  'UZS',
                  'VND',
                  'VUV',
                  'WST',
                  'XAF',
                  'XCD',
                  'XOF',
                  'XPF',
                  'YER',
                  'ZAR',
                  'ZMW',
                ],
              },
              externalId: {
                type: 'string',
              },
              intervalCount: {
                type: 'number',
                description: 'safeZodPositiveInteger',
              },
              intervalUnit: {
                type: 'string',
                enum: ['day', 'week', 'month', 'year'],
              },
              isDefault: {
                type: 'boolean',
              },
              livemode: {
                type: 'boolean',
              },
              name: {
                type: 'string',
              },
              productId: {
                type: 'string',
              },
              setupFeeAmount: {
                anyOf: [
                  {
                    type: 'number',
                    description: 'safeZodPositiveInteger',
                  },
                  {
                    type: 'string',
                    description: 'safeZodPositiveInteger',
                    enum: [0],
                  },
                ],
                description: 'safeZodPositiveInteger',
              },
              trialPeriodDays: {
                anyOf: [
                  {
                    type: 'number',
                    description: 'safeZodPositiveInteger',
                  },
                  {
                    type: 'string',
                    description: 'safeZodPositiveInteger',
                    enum: [0],
                  },
                ],
                description: 'safeZodPositiveInteger',
              },
              unitPrice: {
                type: 'number',
              },
              usageMeterId: {
                type: 'string',
              },
            },
            required: ['id', 'type'],
          },
          {
            type: 'object',
            description:
              'A single payment price, which only gets paid once. Subscriptions cannot be made from single payment prices. Purchases, though, can.',
            properties: {
              id: {
                type: 'string',
              },
              type: {
                type: 'string',
                enum: ['single_payment'],
              },
              active: {
                type: 'boolean',
              },
              currency: {
                type: 'string',
                enum: [
                  'USD',
                  'AED',
                  'AFN',
                  'ALL',
                  'AMD',
                  'ANG',
                  'AOA',
                  'ARS',
                  'AUD',
                  'AWG',
                  'AZN',
                  'BAM',
                  'BBD',
                  'BDT',
                  'BGN',
                  'BIF',
                  'BMD',
                  'BND',
                  'BOB',
                  'BRL',
                  'BSD',
                  'BWP',
                  'BYN',
                  'BZD',
                  'CAD',
                  'CDF',
                  'CHF',
                  'CLP',
                  'CNY',
                  'COP',
                  'CRC',
                  'CVE',
                  'CZK',
                  'DJF',
                  'DKK',
                  'DOP',
                  'DZD',
                  'EGP',
                  'ETB',
                  'EUR',
                  'FJD',
                  'FKP',
                  'GBP',
                  'GEL',
                  'GIP',
                  'GMD',
                  'GNF',
                  'GTQ',
                  'GYD',
                  'HKD',
                  'HNL',
                  'HTG',
                  'HUF',
                  'IDR',
                  'ILS',
                  'INR',
                  'ISK',
                  'JMD',
                  'JPY',
                  'KES',
                  'KGS',
                  'KHR',
                  'KMF',
                  'KRW',
                  'KYD',
                  'KZT',
                  'LAK',
                  'LBP',
                  'LKR',
                  'LRD',
                  'LSL',
                  'MAD',
                  'MDL',
                  'MGA',
                  'MKD',
                  'MMK',
                  'MNT',
                  'MOP',
                  'MUR',
                  'MVR',
                  'MWK',
                  'MXN',
                  'MYR',
                  'MZN',
                  'NAD',
                  'NGN',
                  'NIO',
                  'NOK',
                  'NPR',
                  'NZD',
                  'PAB',
                  'PEN',
                  'PGK',
                  'PHP',
                  'PKR',
                  'PLN',
                  'PYG',
                  'QAR',
                  'RON',
                  'RSD',
                  'RUB',
                  'RWF',
                  'SAR',
                  'SBD',
                  'SCR',
                  'SEK',
                  'SGD',
                  'SHP',
                  'SLE',
                  'SOS',
                  'SRD',
                  'STD',
                  'SZL',
                  'THB',
                  'TJS',
                  'TOP',
                  'TRY',
                  'TTD',
                  'TWD',
                  'TZS',
                  'UAH',
                  'UGX',
                  'UYU',
                  'UZS',
                  'VND',
                  'VUV',
                  'WST',
                  'XAF',
                  'XCD',
                  'XOF',
                  'XPF',
                  'YER',
                  'ZAR',
                  'ZMW',
                ],
              },
              externalId: {
                type: 'string',
              },
              intervalCount: {
                anyOf: [
                  {
                    type: 'string',
                    enum: ['null'],
                  },
                  {
                    type: 'object',
                  },
                ],
                description: 'safeZodNullOrUndefined',
              },
              intervalUnit: {
                anyOf: [
                  {
                    type: 'string',
                    enum: ['null'],
                  },
                  {
                    type: 'object',
                  },
                ],
                description: 'safeZodNullOrUndefined',
              },
              isDefault: {
                type: 'boolean',
              },
              livemode: {
                type: 'boolean',
              },
              name: {
                type: 'string',
              },
              productId: {
                type: 'string',
              },
              setupFeeAmount: {
                anyOf: [
                  {
                    type: 'string',
                    enum: ['null'],
                  },
                  {
                    type: 'object',
                  },
                ],
                description: 'safeZodNullOrUndefined',
              },
              trialPeriodDays: {
                anyOf: [
                  {
                    type: 'string',
                    enum: ['null'],
                  },
                  {
                    type: 'object',
                  },
                ],
                description: 'safeZodNullOrUndefined',
              },
              unitPrice: {
                type: 'number',
              },
              usageMeterId: {
                type: 'string',
              },
            },
            required: ['id', 'type'],
          },
          {
            type: 'object',
            description: 'A usage price, which describes the price per unit of usage of a product.',
            properties: {
              id: {
                type: 'string',
              },
              type: {
                type: 'string',
                enum: ['usage'],
              },
              active: {
                type: 'boolean',
              },
              createdByCommit: {
                type: 'string',
              },
              currency: {
                type: 'string',
                enum: [
                  'USD',
                  'AED',
                  'AFN',
                  'ALL',
                  'AMD',
                  'ANG',
                  'AOA',
                  'ARS',
                  'AUD',
                  'AWG',
                  'AZN',
                  'BAM',
                  'BBD',
                  'BDT',
                  'BGN',
                  'BIF',
                  'BMD',
                  'BND',
                  'BOB',
                  'BRL',
                  'BSD',
                  'BWP',
                  'BYN',
                  'BZD',
                  'CAD',
                  'CDF',
                  'CHF',
                  'CLP',
                  'CNY',
                  'COP',
                  'CRC',
                  'CVE',
                  'CZK',
                  'DJF',
                  'DKK',
                  'DOP',
                  'DZD',
                  'EGP',
                  'ETB',
                  'EUR',
                  'FJD',
                  'FKP',
                  'GBP',
                  'GEL',
                  'GIP',
                  'GMD',
                  'GNF',
                  'GTQ',
                  'GYD',
                  'HKD',
                  'HNL',
                  'HTG',
                  'HUF',
                  'IDR',
                  'ILS',
                  'INR',
                  'ISK',
                  'JMD',
                  'JPY',
                  'KES',
                  'KGS',
                  'KHR',
                  'KMF',
                  'KRW',
                  'KYD',
                  'KZT',
                  'LAK',
                  'LBP',
                  'LKR',
                  'LRD',
                  'LSL',
                  'MAD',
                  'MDL',
                  'MGA',
                  'MKD',
                  'MMK',
                  'MNT',
                  'MOP',
                  'MUR',
                  'MVR',
                  'MWK',
                  'MXN',
                  'MYR',
                  'MZN',
                  'NAD',
                  'NGN',
                  'NIO',
                  'NOK',
                  'NPR',
                  'NZD',
                  'PAB',
                  'PEN',
                  'PGK',
                  'PHP',
                  'PKR',
                  'PLN',
                  'PYG',
                  'QAR',
                  'RON',
                  'RSD',
                  'RUB',
                  'RWF',
                  'SAR',
                  'SBD',
                  'SCR',
                  'SEK',
                  'SGD',
                  'SHP',
                  'SLE',
                  'SOS',
                  'SRD',
                  'STD',
                  'SZL',
                  'THB',
                  'TJS',
                  'TOP',
                  'TRY',
                  'TTD',
                  'TWD',
                  'TZS',
                  'UAH',
                  'UGX',
                  'UYU',
                  'UZS',
                  'VND',
                  'VUV',
                  'WST',
                  'XAF',
                  'XCD',
                  'XOF',
                  'XPF',
                  'YER',
                  'ZAR',
                  'ZMW',
                ],
              },
              externalId: {
                type: 'string',
              },
              intervalCount: {
                type: 'number',
                description: 'safeZodPositiveInteger',
              },
              intervalUnit: {
                type: 'string',
                enum: ['day', 'week', 'month', 'year'],
              },
              isDefault: {
                type: 'boolean',
              },
              livemode: {
                type: 'boolean',
              },
              name: {
                type: 'string',
              },
              productId: {
                type: 'string',
              },
              setupFeeAmount: {
                anyOf: [
                  {
                    type: 'number',
                    description: 'safeZodPositiveInteger',
                  },
                  {
                    type: 'string',
                    description: 'safeZodPositiveInteger',
                    enum: [0],
                  },
                ],
                description: 'safeZodPositiveInteger',
              },
              trialPeriodDays: {
                anyOf: [
                  {
                    type: 'string',
                    enum: ['null'],
                  },
                  {
                    type: 'object',
                  },
                ],
                description: 'safeZodNullOrUndefined',
              },
              unitPrice: {
                type: 'number',
              },
              updatedByCommit: {
                type: 'string',
              },
              usageMeterId: {
                type: 'string',
                description:
                  'The usage meter that uses this price. All usage events on that meter must be associated with a price that is also associated with that usage meter.',
              },
            },
            required: ['id', 'type'],
          },
        ],
        description:
          'A price record, which describes a price for a product. Products can have multiple prices.',
      },
    },
  },
};

export const handler = async (client: Flowglad, args: Record<string, unknown> | undefined) => {
  const { id, ...body } = args as any;
  return asTextContentResult(await client.products.update(id, body));
};

export default { metadata, tool, handler };
