// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from '@flowglad/node-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import Flowglad from '@flowglad/node';

export const metadata: Metadata = {
  resource: 'invoices',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/api/v1/invoices',
  operationId: 'invoices-create',
};

export const tool: Tool = {
  name: 'create_invoices',
  description: 'Create Invoice',
  inputSchema: {
    type: 'object',
    properties: {
      invoice: {
        anyOf: [
          {
            type: 'object',
            description:
              'An invoice created in association with a purchase. This type of invoice is only ever created for single payment prices. Purchases associated with subscriptions will have subscription invoices created instead.',
            properties: {
              billingPeriodId: {
                type: 'string',
                enum: ['null'],
              },
              currency: {
                type: 'string',
                enum: [
                  'USD',
                  'AED',
                  'AFN',
                  'ALL',
                  'AMD',
                  'ANG',
                  'AOA',
                  'ARS',
                  'AUD',
                  'AWG',
                  'AZN',
                  'BAM',
                  'BBD',
                  'BDT',
                  'BGN',
                  'BIF',
                  'BMD',
                  'BND',
                  'BOB',
                  'BRL',
                  'BSD',
                  'BWP',
                  'BYN',
                  'BZD',
                  'CAD',
                  'CDF',
                  'CHF',
                  'CLP',
                  'CNY',
                  'COP',
                  'CRC',
                  'CVE',
                  'CZK',
                  'DJF',
                  'DKK',
                  'DOP',
                  'DZD',
                  'EGP',
                  'ETB',
                  'EUR',
                  'FJD',
                  'FKP',
                  'GBP',
                  'GEL',
                  'GIP',
                  'GMD',
                  'GNF',
                  'GTQ',
                  'GYD',
                  'HKD',
                  'HNL',
                  'HTG',
                  'HUF',
                  'IDR',
                  'ILS',
                  'INR',
                  'ISK',
                  'JMD',
                  'JPY',
                  'KES',
                  'KGS',
                  'KHR',
                  'KMF',
                  'KRW',
                  'KYD',
                  'KZT',
                  'LAK',
                  'LBP',
                  'LKR',
                  'LRD',
                  'LSL',
                  'MAD',
                  'MDL',
                  'MGA',
                  'MKD',
                  'MMK',
                  'MNT',
                  'MOP',
                  'MUR',
                  'MVR',
                  'MWK',
                  'MXN',
                  'MYR',
                  'MZN',
                  'NAD',
                  'NGN',
                  'NIO',
                  'NOK',
                  'NPR',
                  'NZD',
                  'PAB',
                  'PEN',
                  'PGK',
                  'PHP',
                  'PKR',
                  'PLN',
                  'PYG',
                  'QAR',
                  'RON',
                  'RSD',
                  'RUB',
                  'RWF',
                  'SAR',
                  'SBD',
                  'SCR',
                  'SEK',
                  'SGD',
                  'SHP',
                  'SLE',
                  'SOS',
                  'SRD',
                  'STD',
                  'SZL',
                  'THB',
                  'TJS',
                  'TOP',
                  'TRY',
                  'TTD',
                  'TWD',
                  'TZS',
                  'UAH',
                  'UGX',
                  'UYU',
                  'UZS',
                  'VND',
                  'VUV',
                  'WST',
                  'XAF',
                  'XCD',
                  'XOF',
                  'XPF',
                  'YER',
                  'ZAR',
                  'ZMW',
                ],
              },
              customerId: {
                type: 'string',
              },
              invoiceNumber: {
                type: 'string',
              },
              purchaseId: {
                type: 'string',
              },
              subscriptionId: {
                type: 'string',
                enum: ['null'],
              },
              type: {
                type: 'string',
                enum: ['purchase'],
              },
              bankPaymentOnly: {
                type: 'boolean',
              },
              billingPeriodEndDate: {
                type: 'string',
                format: 'date-time',
              },
              billingPeriodStartDate: {
                type: 'string',
                format: 'date-time',
              },
              billingRunId: {
                type: 'string',
              },
              dueDate: {
                type: 'string',
                format: 'date-time',
              },
              invoiceDate: {
                type: 'string',
                format: 'date-time',
              },
              memo: {
                type: 'string',
              },
              ownerMembershipId: {
                type: 'string',
              },
              pdfURL: {
                type: 'string',
              },
              receiptPdfURL: {
                type: 'string',
              },
              status: {
                type: 'string',
                enum: [
                  'draft',
                  'open',
                  'paid',
                  'uncollectible',
                  'void',
                  'refunded',
                  'partially_refunded',
                  'awaiting_payment_confirmation',
                ],
              },
              subtotal: {
                type: 'number',
              },
              taxCountry: {
                type: 'string',
                enum: [
                  'AF',
                  'AL',
                  'DZ',
                  'AS',
                  'AD',
                  'AO',
                  'AI',
                  'AQ',
                  'AG',
                  'AR',
                  'AM',
                  'AW',
                  'AU',
                  'AT',
                  'AZ',
                  'BS',
                  'BH',
                  'BD',
                  'BB',
                  'BY',
                  'BE',
                  'BZ',
                  'BJ',
                  'BM',
                  'BT',
                  'BO',
                  'BA',
                  'BW',
                  'BV',
                  'BR',
                  'IO',
                  'BN',
                  'BG',
                  'BF',
                  'BI',
                  'KH',
                  'CM',
                  'CA',
                  'CV',
                  'KY',
                  'CF',
                  'TD',
                  'CL',
                  'CN',
                  'CX',
                  'CC',
                  'CO',
                  'KM',
                  'CG',
                  'CD',
                  'CK',
                  'CR',
                  'CI',
                  'HR',
                  'CU',
                  'CY',
                  'CZ',
                  'DK',
                  'DJ',
                  'DM',
                  'DO',
                  'EC',
                  'EG',
                  'SV',
                  'GQ',
                  'ER',
                  'EE',
                  'ET',
                  'FK',
                  'FO',
                  'FJ',
                  'FI',
                  'FR',
                  'GF',
                  'PF',
                  'TF',
                  'GA',
                  'GM',
                  'GE',
                  'DE',
                  'GH',
                  'GI',
                  'GR',
                  'GL',
                  'GD',
                  'GP',
                  'GU',
                  'GT',
                  'GN',
                  'GW',
                  'GY',
                  'HT',
                  'HM',
                  'VA',
                  'HN',
                  'HK',
                  'HU',
                  'IS',
                  'IN',
                  'ID',
                  'IR',
                  'IQ',
                  'IE',
                  'IL',
                  'IT',
                  'JM',
                  'JP',
                  'JO',
                  'KZ',
                  'KE',
                  'KI',
                  'KP',
                  'KR',
                  'KW',
                  'KG',
                  'LA',
                  'LV',
                  'LB',
                  'LS',
                  'LR',
                  'LY',
                  'LI',
                  'LT',
                  'LU',
                  'ME',
                  'MO',
                  'MK',
                  'MG',
                  'MW',
                  'MY',
                  'MV',
                  'ML',
                  'MT',
                  'MH',
                  'MQ',
                  'MR',
                  'MU',
                  'YT',
                  'MX',
                  'FM',
                  'MD',
                  'MC',
                  'MN',
                  'MS',
                  'MA',
                  'MZ',
                  'MM',
                  'NA',
                  'NR',
                  'NP',
                  'NL',
                  'NC',
                  'NZ',
                  'NI',
                  'NE',
                  'NG',
                  'NU',
                  'NF',
                  'MP',
                  'NO',
                  'OM',
                  'PK',
                  'PW',
                  'PS',
                  'PA',
                  'PG',
                  'PY',
                  'PE',
                  'PH',
                  'PN',
                  'PL',
                  'PT',
                  'PR',
                  'QA',
                  'RE',
                  'RO',
                  'RU',
                  'RW',
                  'SH',
                  'KN',
                  'LC',
                  'PM',
                  'VC',
                  'WS',
                  'SM',
                  'ST',
                  'SA',
                  'SN',
                  'RS',
                  'SC',
                  'SL',
                  'SG',
                  'SK',
                  'SI',
                  'SB',
                  'SO',
                  'ZA',
                  'GS',
                  'ES',
                  'LK',
                  'SD',
                  'SR',
                  'SJ',
                  'SZ',
                  'SE',
                  'CH',
                  'SY',
                  'TW',
                  'TJ',
                  'TZ',
                  'TH',
                  'TL',
                  'TG',
                  'TK',
                  'TO',
                  'TT',
                  'TN',
                  'TR',
                  'TM',
                  'TC',
                  'TV',
                  'UG',
                  'UA',
                  'AE',
                  'GB',
                  'US',
                  'UM',
                  'UY',
                  'UZ',
                  'VU',
                  'VE',
                  'VN',
                  'VG',
                  'VI',
                  'WF',
                  'EH',
                  'YE',
                  'ZM',
                  'ZW',
                ],
              },
              taxState: {
                type: 'string',
              },
              taxType: {
                type: 'string',
                enum: [
                  'amusement_tax',
                  'communications_tax',
                  'gst',
                  'hst',
                  'igst',
                  'jct',
                  'lease_tax',
                  'pst',
                  'qst',
                  'rst',
                  'sales_tax',
                  'vat',
                  'none',
                ],
              },
            },
            required: [
              'billingPeriodId',
              'currency',
              'customerId',
              'invoiceNumber',
              'purchaseId',
              'subscriptionId',
              'type',
            ],
          },
          {
            type: 'object',
            description:
              'An invoice created in association with a subscription. This type of invoice is only ever created for subscription prices. Purchases associated with single payment prices will have purchase invoices created instead.',
            properties: {
              billingPeriodId: {
                type: 'string',
              },
              currency: {
                type: 'string',
                enum: [
                  'USD',
                  'AED',
                  'AFN',
                  'ALL',
                  'AMD',
                  'ANG',
                  'AOA',
                  'ARS',
                  'AUD',
                  'AWG',
                  'AZN',
                  'BAM',
                  'BBD',
                  'BDT',
                  'BGN',
                  'BIF',
                  'BMD',
                  'BND',
                  'BOB',
                  'BRL',
                  'BSD',
                  'BWP',
                  'BYN',
                  'BZD',
                  'CAD',
                  'CDF',
                  'CHF',
                  'CLP',
                  'CNY',
                  'COP',
                  'CRC',
                  'CVE',
                  'CZK',
                  'DJF',
                  'DKK',
                  'DOP',
                  'DZD',
                  'EGP',
                  'ETB',
                  'EUR',
                  'FJD',
                  'FKP',
                  'GBP',
                  'GEL',
                  'GIP',
                  'GMD',
                  'GNF',
                  'GTQ',
                  'GYD',
                  'HKD',
                  'HNL',
                  'HTG',
                  'HUF',
                  'IDR',
                  'ILS',
                  'INR',
                  'ISK',
                  'JMD',
                  'JPY',
                  'KES',
                  'KGS',
                  'KHR',
                  'KMF',
                  'KRW',
                  'KYD',
                  'KZT',
                  'LAK',
                  'LBP',
                  'LKR',
                  'LRD',
                  'LSL',
                  'MAD',
                  'MDL',
                  'MGA',
                  'MKD',
                  'MMK',
                  'MNT',
                  'MOP',
                  'MUR',
                  'MVR',
                  'MWK',
                  'MXN',
                  'MYR',
                  'MZN',
                  'NAD',
                  'NGN',
                  'NIO',
                  'NOK',
                  'NPR',
                  'NZD',
                  'PAB',
                  'PEN',
                  'PGK',
                  'PHP',
                  'PKR',
                  'PLN',
                  'PYG',
                  'QAR',
                  'RON',
                  'RSD',
                  'RUB',
                  'RWF',
                  'SAR',
                  'SBD',
                  'SCR',
                  'SEK',
                  'SGD',
                  'SHP',
                  'SLE',
                  'SOS',
                  'SRD',
                  'STD',
                  'SZL',
                  'THB',
                  'TJS',
                  'TOP',
                  'TRY',
                  'TTD',
                  'TWD',
                  'TZS',
                  'UAH',
                  'UGX',
                  'UYU',
                  'UZS',
                  'VND',
                  'VUV',
                  'WST',
                  'XAF',
                  'XCD',
                  'XOF',
                  'XPF',
                  'YER',
                  'ZAR',
                  'ZMW',
                ],
              },
              customerId: {
                type: 'string',
              },
              invoiceNumber: {
                type: 'string',
              },
              purchaseId: {
                type: 'string',
                enum: ['null'],
              },
              subscriptionId: {
                type: 'string',
              },
              type: {
                type: 'string',
                enum: ['subscription'],
              },
              bankPaymentOnly: {
                type: 'boolean',
              },
              billingPeriodEndDate: {
                type: 'string',
                format: 'date-time',
              },
              billingPeriodStartDate: {
                type: 'string',
                format: 'date-time',
              },
              billingRunId: {
                type: 'string',
              },
              dueDate: {
                type: 'string',
                format: 'date-time',
              },
              invoiceDate: {
                type: 'string',
                format: 'date-time',
              },
              memo: {
                type: 'string',
              },
              ownerMembershipId: {
                type: 'string',
              },
              pdfURL: {
                type: 'string',
              },
              receiptPdfURL: {
                type: 'string',
              },
              status: {
                type: 'string',
                enum: [
                  'draft',
                  'open',
                  'paid',
                  'uncollectible',
                  'void',
                  'refunded',
                  'partially_refunded',
                  'awaiting_payment_confirmation',
                ],
              },
              subtotal: {
                type: 'number',
              },
              taxCountry: {
                type: 'string',
                enum: [
                  'AF',
                  'AL',
                  'DZ',
                  'AS',
                  'AD',
                  'AO',
                  'AI',
                  'AQ',
                  'AG',
                  'AR',
                  'AM',
                  'AW',
                  'AU',
                  'AT',
                  'AZ',
                  'BS',
                  'BH',
                  'BD',
                  'BB',
                  'BY',
                  'BE',
                  'BZ',
                  'BJ',
                  'BM',
                  'BT',
                  'BO',
                  'BA',
                  'BW',
                  'BV',
                  'BR',
                  'IO',
                  'BN',
                  'BG',
                  'BF',
                  'BI',
                  'KH',
                  'CM',
                  'CA',
                  'CV',
                  'KY',
                  'CF',
                  'TD',
                  'CL',
                  'CN',
                  'CX',
                  'CC',
                  'CO',
                  'KM',
                  'CG',
                  'CD',
                  'CK',
                  'CR',
                  'CI',
                  'HR',
                  'CU',
                  'CY',
                  'CZ',
                  'DK',
                  'DJ',
                  'DM',
                  'DO',
                  'EC',
                  'EG',
                  'SV',
                  'GQ',
                  'ER',
                  'EE',
                  'ET',
                  'FK',
                  'FO',
                  'FJ',
                  'FI',
                  'FR',
                  'GF',
                  'PF',
                  'TF',
                  'GA',
                  'GM',
                  'GE',
                  'DE',
                  'GH',
                  'GI',
                  'GR',
                  'GL',
                  'GD',
                  'GP',
                  'GU',
                  'GT',
                  'GN',
                  'GW',
                  'GY',
                  'HT',
                  'HM',
                  'VA',
                  'HN',
                  'HK',
                  'HU',
                  'IS',
                  'IN',
                  'ID',
                  'IR',
                  'IQ',
                  'IE',
                  'IL',
                  'IT',
                  'JM',
                  'JP',
                  'JO',
                  'KZ',
                  'KE',
                  'KI',
                  'KP',
                  'KR',
                  'KW',
                  'KG',
                  'LA',
                  'LV',
                  'LB',
                  'LS',
                  'LR',
                  'LY',
                  'LI',
                  'LT',
                  'LU',
                  'ME',
                  'MO',
                  'MK',
                  'MG',
                  'MW',
                  'MY',
                  'MV',
                  'ML',
                  'MT',
                  'MH',
                  'MQ',
                  'MR',
                  'MU',
                  'YT',
                  'MX',
                  'FM',
                  'MD',
                  'MC',
                  'MN',
                  'MS',
                  'MA',
                  'MZ',
                  'MM',
                  'NA',
                  'NR',
                  'NP',
                  'NL',
                  'NC',
                  'NZ',
                  'NI',
                  'NE',
                  'NG',
                  'NU',
                  'NF',
                  'MP',
                  'NO',
                  'OM',
                  'PK',
                  'PW',
                  'PS',
                  'PA',
                  'PG',
                  'PY',
                  'PE',
                  'PH',
                  'PN',
                  'PL',
                  'PT',
                  'PR',
                  'QA',
                  'RE',
                  'RO',
                  'RU',
                  'RW',
                  'SH',
                  'KN',
                  'LC',
                  'PM',
                  'VC',
                  'WS',
                  'SM',
                  'ST',
                  'SA',
                  'SN',
                  'RS',
                  'SC',
                  'SL',
                  'SG',
                  'SK',
                  'SI',
                  'SB',
                  'SO',
                  'ZA',
                  'GS',
                  'ES',
                  'LK',
                  'SD',
                  'SR',
                  'SJ',
                  'SZ',
                  'SE',
                  'CH',
                  'SY',
                  'TW',
                  'TJ',
                  'TZ',
                  'TH',
                  'TL',
                  'TG',
                  'TK',
                  'TO',
                  'TT',
                  'TN',
                  'TR',
                  'TM',
                  'TC',
                  'TV',
                  'UG',
                  'UA',
                  'AE',
                  'GB',
                  'US',
                  'UM',
                  'UY',
                  'UZ',
                  'VU',
                  'VE',
                  'VN',
                  'VG',
                  'VI',
                  'WF',
                  'EH',
                  'YE',
                  'ZM',
                  'ZW',
                ],
              },
              taxState: {
                type: 'string',
              },
              taxType: {
                type: 'string',
                enum: [
                  'amusement_tax',
                  'communications_tax',
                  'gst',
                  'hst',
                  'igst',
                  'jct',
                  'lease_tax',
                  'pst',
                  'qst',
                  'rst',
                  'sales_tax',
                  'vat',
                  'none',
                ],
              },
            },
            required: [
              'billingPeriodId',
              'currency',
              'customerId',
              'invoiceNumber',
              'purchaseId',
              'subscriptionId',
              'type',
            ],
          },
          {
            type: 'object',
            description:
              'An invoice created without any associated purchase or subscription. These invoices are most often created manually.',
            properties: {
              billingPeriodId: {
                type: 'string',
                enum: ['null'],
              },
              currency: {
                type: 'string',
                enum: [
                  'USD',
                  'AED',
                  'AFN',
                  'ALL',
                  'AMD',
                  'ANG',
                  'AOA',
                  'ARS',
                  'AUD',
                  'AWG',
                  'AZN',
                  'BAM',
                  'BBD',
                  'BDT',
                  'BGN',
                  'BIF',
                  'BMD',
                  'BND',
                  'BOB',
                  'BRL',
                  'BSD',
                  'BWP',
                  'BYN',
                  'BZD',
                  'CAD',
                  'CDF',
                  'CHF',
                  'CLP',
                  'CNY',
                  'COP',
                  'CRC',
                  'CVE',
                  'CZK',
                  'DJF',
                  'DKK',
                  'DOP',
                  'DZD',
                  'EGP',
                  'ETB',
                  'EUR',
                  'FJD',
                  'FKP',
                  'GBP',
                  'GEL',
                  'GIP',
                  'GMD',
                  'GNF',
                  'GTQ',
                  'GYD',
                  'HKD',
                  'HNL',
                  'HTG',
                  'HUF',
                  'IDR',
                  'ILS',
                  'INR',
                  'ISK',
                  'JMD',
                  'JPY',
                  'KES',
                  'KGS',
                  'KHR',
                  'KMF',
                  'KRW',
                  'KYD',
                  'KZT',
                  'LAK',
                  'LBP',
                  'LKR',
                  'LRD',
                  'LSL',
                  'MAD',
                  'MDL',
                  'MGA',
                  'MKD',
                  'MMK',
                  'MNT',
                  'MOP',
                  'MUR',
                  'MVR',
                  'MWK',
                  'MXN',
                  'MYR',
                  'MZN',
                  'NAD',
                  'NGN',
                  'NIO',
                  'NOK',
                  'NPR',
                  'NZD',
                  'PAB',
                  'PEN',
                  'PGK',
                  'PHP',
                  'PKR',
                  'PLN',
                  'PYG',
                  'QAR',
                  'RON',
                  'RSD',
                  'RUB',
                  'RWF',
                  'SAR',
                  'SBD',
                  'SCR',
                  'SEK',
                  'SGD',
                  'SHP',
                  'SLE',
                  'SOS',
                  'SRD',
                  'STD',
                  'SZL',
                  'THB',
                  'TJS',
                  'TOP',
                  'TRY',
                  'TTD',
                  'TWD',
                  'TZS',
                  'UAH',
                  'UGX',
                  'UYU',
                  'UZS',
                  'VND',
                  'VUV',
                  'WST',
                  'XAF',
                  'XCD',
                  'XOF',
                  'XPF',
                  'YER',
                  'ZAR',
                  'ZMW',
                ],
              },
              customerId: {
                type: 'string',
              },
              invoiceNumber: {
                type: 'string',
              },
              purchaseId: {
                type: 'string',
                enum: ['null'],
              },
              subscriptionId: {
                type: 'string',
                enum: ['null'],
              },
              type: {
                type: 'string',
                enum: ['standalone'],
              },
              bankPaymentOnly: {
                type: 'boolean',
              },
              billingPeriodEndDate: {
                type: 'string',
                format: 'date-time',
              },
              billingPeriodStartDate: {
                type: 'string',
                format: 'date-time',
              },
              billingRunId: {
                type: 'string',
              },
              dueDate: {
                type: 'string',
                format: 'date-time',
              },
              invoiceDate: {
                type: 'string',
                format: 'date-time',
              },
              memo: {
                type: 'string',
              },
              ownerMembershipId: {
                type: 'string',
              },
              pdfURL: {
                type: 'string',
              },
              receiptPdfURL: {
                type: 'string',
              },
              status: {
                type: 'string',
                enum: [
                  'draft',
                  'open',
                  'paid',
                  'uncollectible',
                  'void',
                  'refunded',
                  'partially_refunded',
                  'awaiting_payment_confirmation',
                ],
              },
              subtotal: {
                type: 'number',
              },
              taxCountry: {
                type: 'string',
                enum: [
                  'AF',
                  'AL',
                  'DZ',
                  'AS',
                  'AD',
                  'AO',
                  'AI',
                  'AQ',
                  'AG',
                  'AR',
                  'AM',
                  'AW',
                  'AU',
                  'AT',
                  'AZ',
                  'BS',
                  'BH',
                  'BD',
                  'BB',
                  'BY',
                  'BE',
                  'BZ',
                  'BJ',
                  'BM',
                  'BT',
                  'BO',
                  'BA',
                  'BW',
                  'BV',
                  'BR',
                  'IO',
                  'BN',
                  'BG',
                  'BF',
                  'BI',
                  'KH',
                  'CM',
                  'CA',
                  'CV',
                  'KY',
                  'CF',
                  'TD',
                  'CL',
                  'CN',
                  'CX',
                  'CC',
                  'CO',
                  'KM',
                  'CG',
                  'CD',
                  'CK',
                  'CR',
                  'CI',
                  'HR',
                  'CU',
                  'CY',
                  'CZ',
                  'DK',
                  'DJ',
                  'DM',
                  'DO',
                  'EC',
                  'EG',
                  'SV',
                  'GQ',
                  'ER',
                  'EE',
                  'ET',
                  'FK',
                  'FO',
                  'FJ',
                  'FI',
                  'FR',
                  'GF',
                  'PF',
                  'TF',
                  'GA',
                  'GM',
                  'GE',
                  'DE',
                  'GH',
                  'GI',
                  'GR',
                  'GL',
                  'GD',
                  'GP',
                  'GU',
                  'GT',
                  'GN',
                  'GW',
                  'GY',
                  'HT',
                  'HM',
                  'VA',
                  'HN',
                  'HK',
                  'HU',
                  'IS',
                  'IN',
                  'ID',
                  'IR',
                  'IQ',
                  'IE',
                  'IL',
                  'IT',
                  'JM',
                  'JP',
                  'JO',
                  'KZ',
                  'KE',
                  'KI',
                  'KP',
                  'KR',
                  'KW',
                  'KG',
                  'LA',
                  'LV',
                  'LB',
                  'LS',
                  'LR',
                  'LY',
                  'LI',
                  'LT',
                  'LU',
                  'ME',
                  'MO',
                  'MK',
                  'MG',
                  'MW',
                  'MY',
                  'MV',
                  'ML',
                  'MT',
                  'MH',
                  'MQ',
                  'MR',
                  'MU',
                  'YT',
                  'MX',
                  'FM',
                  'MD',
                  'MC',
                  'MN',
                  'MS',
                  'MA',
                  'MZ',
                  'MM',
                  'NA',
                  'NR',
                  'NP',
                  'NL',
                  'NC',
                  'NZ',
                  'NI',
                  'NE',
                  'NG',
                  'NU',
                  'NF',
                  'MP',
                  'NO',
                  'OM',
                  'PK',
                  'PW',
                  'PS',
                  'PA',
                  'PG',
                  'PY',
                  'PE',
                  'PH',
                  'PN',
                  'PL',
                  'PT',
                  'PR',
                  'QA',
                  'RE',
                  'RO',
                  'RU',
                  'RW',
                  'SH',
                  'KN',
                  'LC',
                  'PM',
                  'VC',
                  'WS',
                  'SM',
                  'ST',
                  'SA',
                  'SN',
                  'RS',
                  'SC',
                  'SL',
                  'SG',
                  'SK',
                  'SI',
                  'SB',
                  'SO',
                  'ZA',
                  'GS',
                  'ES',
                  'LK',
                  'SD',
                  'SR',
                  'SJ',
                  'SZ',
                  'SE',
                  'CH',
                  'SY',
                  'TW',
                  'TJ',
                  'TZ',
                  'TH',
                  'TL',
                  'TG',
                  'TK',
                  'TO',
                  'TT',
                  'TN',
                  'TR',
                  'TM',
                  'TC',
                  'TV',
                  'UG',
                  'UA',
                  'AE',
                  'GB',
                  'US',
                  'UM',
                  'UY',
                  'UZ',
                  'VU',
                  'VE',
                  'VN',
                  'VG',
                  'VI',
                  'WF',
                  'EH',
                  'YE',
                  'ZM',
                  'ZW',
                ],
              },
              taxState: {
                type: 'string',
              },
              taxType: {
                type: 'string',
                enum: [
                  'amusement_tax',
                  'communications_tax',
                  'gst',
                  'hst',
                  'igst',
                  'jct',
                  'lease_tax',
                  'pst',
                  'qst',
                  'rst',
                  'sales_tax',
                  'vat',
                  'none',
                ],
              },
            },
            required: [
              'billingPeriodId',
              'currency',
              'customerId',
              'invoiceNumber',
              'purchaseId',
              'subscriptionId',
              'type',
            ],
          },
        ],
        description:
          'An invoice record, which describes a bill that can be associated with a purchase, subscription, or stand alone. Each invoice has a specific type that determines its behavior and required fields.',
      },
      invoiceLineItems: {
        type: 'array',
        items: {
          anyOf: [
            {
              type: 'object',
              description: 'A static invoice line item, representing a fixed fee component of an invoice.',
              properties: {
                description: {
                  type: 'string',
                },
                price: {
                  type: 'number',
                },
                priceId: {
                  type: 'string',
                },
                quantity: {
                  type: 'number',
                  description: 'safeZodPositiveInteger',
                },
                type: {
                  type: 'string',
                  enum: ['static'],
                },
              },
              required: ['description', 'price', 'priceId', 'quantity', 'type'],
            },
            {
              type: 'object',
              description:
                'A usage-based invoice line item, where charges are based on recorded usage events.',
              properties: {
                description: {
                  type: 'string',
                },
                price: {
                  type: 'number',
                },
                priceId: {
                  type: 'string',
                },
                quantity: {
                  type: 'number',
                  description: 'safeZodPositiveInteger',
                },
                type: {
                  type: 'string',
                  enum: ['usage'],
                },
              },
              required: ['description', 'price', 'priceId', 'quantity', 'type'],
            },
          ],
          description: 'A static invoice line item, representing a fixed fee component of an invoice.',
        },
      },
      autoSend: {
        type: 'boolean',
      },
    },
  },
};

export const handler = async (client: Flowglad, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return asTextContentResult(await client.invoices.create(body));
};

export default { metadata, tool, handler };
